### ISSUE TITLE
Jitter on develop builds using NVIDIA decoder

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1440]
I am having heavy jittering on one channel. all the files for this channel are mp4 format. I am using hls segmenter as the format for streaming. This is the only channel having this issue. here is part of the log below from the logs page. 

<html><body>

9/21/2023 11:11:05 PM -05:00 | Information | ffmpeg hls  arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error  -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -c:v h264_cuvid  -hwaccel_output_format cuda -readrate 1.0 -readrate_initial_burst 5 -i  "\\MINGOSERVER\Media\TV Shows\House M.D. (2004)\Season 05\S05x04 -  Birthmarks.mkv" -filter_complex  [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=2638635ms[a];[0:0]scale_cuda=iw*sar:ih:format=nv12,setsar=1,scale_cuda=1920:1080:format=nv12:force_original_aspect_ratio=decrease,hwdownload,format=nv12,pad=1920:1080:-1:-1:color=black[v];[v]setparams=range=tv:colorspace=bt709:color_trc=bt709:color_primaries=bt709[vpf]  -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart  -flags cgop -sc_threshold 0 -t 00:43:58.6350000 -video_track_timescale  90000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v h264_nvenc  -pix_fmt yuv420p -output_ts_offset 1254.5439777777779 -c:a aac -b:a 192k  -maxrate:a 192k -bufsize:a 384k -ar 48k -map_metadata -1 -metadata  "service_provider=\"ErsatzTV\"" -metadata "service_name=\"House M.D.\""  -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*4) -f hls  -hls_time 4 -hls_list_size 0 -segment_list_flags +live  -hls_segment_filename "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\93\live%06d.ts" -hls_flags  program_date_time+append_list+discont_start+omit_endlist+independent_segments  -mpegts_flags +initial_discontinuity "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\93\live.m3u8"
-- | -- | --
9/21/2023 11:11:05 PM -05:00 | Information | Forcing 1 ffmpeg thread when hardware acceleration is used
9/21/2023 11:11:05 PM -05:00 | Debug | Format ["nv12"] doesn't equal yuv420p
9/21/2023 11:11:05 PM -05:00 | Debug | FFmpeg  pipeline  ["ThreadCountOption","NoStandardInputOption","HideBannerOption","NoStatsOption","LoglevelErrorOption","StandardFormatFlags","NoDemuxDecodeDelayOutputOption","FastStartOutputOption","ClosedGopOutputOption","NoSceneDetectOutputOption","TimeLimitOutputOption","CudaHardwareAccelerationOption","VideoTrackTimescaleOutputOption","VideoBitrateOutputOption","VideoBufferSizeOutputOption","EncoderH264Nvenc","PixelFormatOutputOption","OutputTsOffsetOption","EncoderAac","AudioChannelsOutputOption","AudioBitrateOutputOption","AudioBufferSizeOutputOption","AudioSampleRateOutputOption","DoNotMapMetadataOutputOption","MetadataServiceProviderOutputOption","MetadataServiceNameOutputOption","OutputFormatHls","ComplexFilter"],  ["NormalizeLoudnessFilter","AudioPadFilter"],  ["ScaleCudaFilter","PadFilter","EncoderH264Nvenc"]
9/21/2023 11:11:04 PM -05:00 | Debug | Checking for JS Script at C:\Users\Mingo Arcade\AppData\Local\ersatztv\scripts\audio-stream-selector\episode.js
9/21/2023 11:11:04 PM -05:00 | Debug | Unable to locate episode audio stream selector script; falling back to built-in logic
9/21/2023 11:11:04 PM -05:00 | Debug | SelectAudioStream duration: "00:00:00.0002035"
9/21/2023 11:11:04 PM -05:00 | Debug | Unable to find audio stream with preferred audio language code(s) ["eng"]
9/21/2023 11:11:04 PM -05:00 | Debug | Found audio stream flagged as default
9/21/2023 11:11:04 PM -05:00 | Debug | FFmpeg  desired state FrameState { Realtime = True, InfiniteLoop = False,  VideoFormat = h264, VideoProfile = Some(high), PixelFormat =  Some(ErsatzTV.FFmpeg.Format.PixelFormatYuv420P), ScaledSize = FrameSize {  Width = 1919, Height = 1080 }, PaddedSize = FrameSize { Width = 1920,  Height = 1080 }, IsAnamorphic = False, FrameRate = None, VideoBitrate =  Some(2000), VideoBufferSize = Some(4000), VideoTrackTimeScale =  Some(90000), Deinterlaced = False, FrameDataLocation = Unknown,  FFmpegAspectRatio = 16/9, BitDepth = 8 }
9/21/2023 11:11:04 PM -05:00 | Information | HLS session state: "ZeroAndRealtime"
9/21/2023 11:11:04 PM -05:00 | Information | HLS segmenter will NOT work ahead for channel 93
9/21/2023 11:11:04 PM -05:00 | Debug | HLS session state throttling "ZeroAndWorkAhead" => "ZeroAndRealtime"
9/21/2023 11:09:18 PM -05:00 | Debug | Completed garbage collection
9/21/2023 11:09:18 PM -05:00 | Debug | Starting garbage collection
9/21/2023 11:09:18 PM -05:00 | Information | Terminating HLS process for channel 43
9/21/2023 11:09:04 PM -05:00 | Information | HLS process has completed for channel 93

</body>
</html>

**Comment by Domjen2521** [comment]
here is the actual log file for the day. 
[ersatztv20230921.log](https://github.com/ErsatzTV/ErsatzTV/files/12696740/ersatztv20230921.log)

**Comment by jasongdove** [comment]
Thanks for the report; someone else reported the same issue in Discord. I'll get my NVIDIA setup going again and take a look.

**Comment by Domjen2521** [comment]
I updated to v0.8.2-58fae1b0-win-x64. the issue is still present. please let me know if you need any more logs or information.

**Comment by Domjen2521** [comment]
issue still present on version v0.8.2-bc845b13-win-x64 will update to current development asap.

**Comment by jasongdove** [comment]
There are a couple of strange issues with NVIDIA and Windows in develop builds (specifically because they use ffmpeg 6.1 snapshot builds). I wouldn't expect anything to improve until something changes with ffmpeg. I'm keeping my eye on things, and will post here with any updates.

**Comment by jasongdove** [comment]
@Domjen2521 - the latest develop build contains an update ffmpeg. Please let me know if it improves your NVIDIA playback.

**Comment by Domjen2521** [comment]
The issue seems to have been resolved. watched and waited for an error and it did not occur.

**Comment by Domjen2521** [comment]
I am going to have to start testing for more than 5 hours. after watching the channel for quite some time. it started happening again. albeit in a different stylized manner. 
![ScreenHunter_389 Oct  06 15 36](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/e8ced506-4dab-4046-bc07-ab20ab930d7c)
![ScreenHunter_390 Oct  06 15 36](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/00d1584e-874c-428e-b1db-7cf793feb5d3)


also here is the log
[ersatztv20231006.log](https://github.com/ErsatzTV/ErsatzTV/files/12835333/ersatztv20231006.log)

**Comment by Domjen2521** [comment]
Ok update, i have left this bad boy running for a few hours. while the issue occurred off and on, mostly on. using ersatzTV versionv0.8.2-c3fe2639-win-x64. Will update to the newest one tonight and see if it persists. here is the screen shots and logs  for the day showing the same jitter issue.  The issue is still present for channel 93. which are mp4 files. it doesnt always happen immediately. hope these logs help.

![ScreenHunter_391 Oct  08 23 21](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/5ff41f36-b51e-4c6b-b957-608f255f7b6d)
![ScreenHunter_392 Oct  08 23 22](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/a7fec20f-020d-4cf0-80e0-babcb09a146c)
[ersatztv20231008.log](https://github.com/ErsatzTV/ErsatzTV/files/12842660/ersatztv20231008.log)

**Comment by merrychrishna** [comment]
yes jerky, jitter, glitching video. imm the one who reported it on discord. its still happening after the new update.

**Comment by jasongdove** [comment]
I can confirm the same behavior on Linux. Seems related to the source content; would like to find a pattern so I don't have to avoid all NVIDIA hardware-accelerated decoding.

**Comment by Domjen2521** [comment]
Almost all content i have runs on MKV H264. Even the MP4 files are H264. the other day some mkv files started having issues. for only one show. i will see if it happens again on that one program. updated to the current one and mp4 seems to be roughly working. with mild conversion rate. will look into it and get logs asap.

**Comment by Domjen2521** [comment]
I rolled back to ffmpeg version n5.0.1-7-g7389a49fd3-20220630, before the new ersatz update and now on v0.8.2-f5060522-win-x64. the issue is not present with the new update. the only hiccup is the delay when doing software conversion. it does not happen a lot, just a bit now and then, you have to be watching it to catch it. i think it is when it is starting a new conversion process. here are the logs for today and the last two days. 

[ersatztv20231015.log](https://github.com/ErsatzTV/ErsatzTV/files/12952658/ersatztv20231015.log)
[ersatztv20231016.log](https://github.com/ErsatzTV/ErsatzTV/files/12952672/ersatztv20231016.log)
[ersatztv20231017.log](https://github.com/ErsatzTV/ErsatzTV/files/12952682/ersatztv20231017.log)

**Comment by jasongdove** [comment]
I reported this as an ffmpeg bug and it seems to be confirmed as a regression, at least. Hoping a fix is straightforward so I can re-enable hardware decoding with NVIDIA.

https://trac.ffmpeg.org/ticket/10668

**Comment by jasongdove** [comment]
A workaround to fix nvidia hardware decoding in docker was added with https://github.com/ErsatzTV/ErsatzTV-ffmpeg/pull/10 and is available on develop builds now.

I'm considering creating an ErsatzTV-specific Windows ffmpeg build to include a similar workaround.

**Comment by Domjen2521** [comment]
@jasongdove I wanted to let you know, that i had not seen the issue appear in quite some time. I wanted to give you the opportunity to close this one yourself since it is working on my end and the resolution seems to be effective.
